name: bootstrap workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: run boostrap.sh
      run: |
        ./bootstrap.sh
    - name: Run tests
      run: |
        cd givitsite
        pipenv run pytest -s -v
        
    - if: github.event.pull_request.merged == true 
      name: Agura test
      run: echo "agura test" 
